# -*- coding: utf-8 -*-
"""online retail sales .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MSH7qshSEESql_EF340cMl0xw4gMNvN8
"""

import pandas as pd
import numpy as np

df=pd.read_csv('online_retail.csv' , encoding='ISO-8859-1')

df.head()

df.info()

df.describe()

print("Before:",len(df))

df=df.dropna(subset=["CustomerID"])
print(len(df))

df=df[df["Quantity"]>0]
print(len(df))

df=df.drop_duplicates()
print(len(df))

df["Total price"]=df["Quantity"] * df["UnitPrice"]

df["Total price"]

df

df["InvoiceDate"]=pd.to_datetime(df["InvoiceDate"])

import datetime as dt

snapshot_date=df["InvoiceDate"].max() + dt.timedelta(days=1)

print("Snapshot date:", snapshot_date)

rfm=df.groupby("CustomerID").agg({
    "InvoiceDate":lambda x: (snapshot_date-x.max()).days,
    "InvoiceNo": lambda x: len(x),
    "Total price": lambda x: x.sum()
})

rfm.columns=["Recency","Frequency","Monetary"]

rfm.head()

rfm["R_score"] = pd.qcut(rfm["Recency"],4,labels=[4,3,2,1])
rfm["F_score"] = pd.qcut(rfm["Frequency"].rank(method="first"),4,labels=[4,3,2,1])
rfm["M_score"] = pd.qcut(rfm["Monetary"],4,labels=[4,3,2,1])

rfm["RFM_score"]=rfm["R_score"].astype(str)+rfm["F_score"].astype(str)+rfm["M_score"].astype(str)

def segment(row):
    if row['RFM_score'] in ['444','443','434']:
        return 'Champions'
    elif row['R_score'] == 4:
        return 'Recent Customers'
    elif row['F_score'] == 4:
        return 'Loyal Customers'
    elif row['R_score'] == 1:
        return 'At Risk'
    else:
        return 'Others'

rfm['Segment'] = rfm.apply(segment, axis=1)
rfm['Segment'].value_counts()

rfm.to_csv("customer_segments.csv")
df.to_csv("cleaned_transactions.csv", index=False)

